// daily phrases. MAX WORD LENGTH OF BOXCOLS. TOTAL CHARACTERS IS 90
// BANNED CHARACTERS: "^", "-";


// const PHRASES = "BITE THE -BULLET-PROOF -PLAN- OF -ACTION-S SPEAK \
// LOUDER THAN -WORDS- OF -WISDOM- -TEETH-ING -PUPPY- -LOVE- ONE -ANOTHER- \
// ONE BITES THE -DUST-ING -OFF- THE BEATEN PATH"


const PHRASES = "FUZZY -PEACH- -STATE- OF THE UNION -ADDRESS- A \
-PROBLEM-ATIC PEOPLE"


// const PHRASES = "EXTREMELY FAST AND ROGUE -BULLET--PROOF- -GLASS- \
// HALF -EMPTY- ON THE -INSIDE- -VOICE-S OF -TRUTH- BE TOLD"


// const PHRASES = "ONE MUST BE QUICK THROUGH THE AIR LIKE A SPEEDING \
// -BULLET--PROOF--READ-Y FOR ANYTHING"


// const PHRASES = "BULLET-PROOF--READ- A CLASSMATES ESSAY FOR A GRADE IN A VERY \
// DIFFICULT CLASS IN -COLLEGE- MIDTERMS"


// const PHRASES = "I LIKE -MILK BONES- ARE -GOOD- -GRIEF-ING A HU-MAN--SLAUGHTER-HOUSE"


// const PHRASES = "GO THE EXTRA -MILE- -HIGH- -FIVE- OCLOCK -SHADOW- OF A -DOUBT--LESS- IS -MORE- \
// OR LESS"


// const PHRASES = "FUZZY -PEACH-ES"



export { PHRASES };